export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const LIKE_IMAGE = 'LIKE_IMAGE';
export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
